using System.Runtime.CompilerServices;

namespace Hezium.Memory;

[InlineArray(1)] struct ElementChunk1<TElement> { private TElement _first; }
[InlineArray(2)] struct ElementChunk2<TElement> { private TElement _first; }
[InlineArray(3)] struct ElementChunk3<TElement> { private TElement _first; }
[InlineArray(5)] struct ElementChunk5<TElement> { private TElement _first; }
[InlineArray(7)] struct ElementChunk7<TElement> { private TElement _first; }
[InlineArray(11)] struct ElementChunk11<TElement> { private TElement _first; }
[InlineArray(13)] struct ElementChunk13<TElement> { private TElement _first; }
[InlineArray(17)] struct ElementChunk17<TElement> { private TElement _first; }
[InlineArray(19)] struct ElementChunk19<TElement> { private TElement _first; }
[InlineArray(23)] struct ElementChunk23<TElement> { private TElement _first; }
[InlineArray(29)] struct ElementChunk29<TElement> { private TElement _first; }
[InlineArray(31)] struct ElementChunk31<TElement> { private TElement _first; }
[InlineArray(37)] struct ElementChunk37<TElement> { private TElement _first; }
[InlineArray(41)] struct ElementChunk41<TElement> { private TElement _first; }
[InlineArray(43)] struct ElementChunk43<TElement> { private TElement _first; }
[InlineArray(47)] struct ElementChunk47<TElement> { private TElement _first; }
[InlineArray(53)] struct ElementChunk53<TElement> { private TElement _first; }
[InlineArray(59)] struct ElementChunk59<TElement> { private TElement _first; }
[InlineArray(61)] struct ElementChunk61<TElement> { private TElement _first; }
[InlineArray(67)] struct ElementChunk67<TElement> { private TElement _first; }
[InlineArray(71)] struct ElementChunk71<TElement> { private TElement _first; }
[InlineArray(73)] struct ElementChunk73<TElement> { private TElement _first; }
[InlineArray(79)] struct ElementChunk79<TElement> { private TElement _first; }
[InlineArray(83)] struct ElementChunk83<TElement> { private TElement _first; }
[InlineArray(89)] struct ElementChunk89<TElement> { private TElement _first; }
[InlineArray(97)] struct ElementChunk97<TElement> { private TElement _first; }
[InlineArray(101)] struct ElementChunk101<TElement> { private TElement _first; }
[InlineArray(103)] struct ElementChunk103<TElement> { private TElement _first; }
[InlineArray(107)] struct ElementChunk107<TElement> { private TElement _first; }
[InlineArray(109)] struct ElementChunk109<TElement> { private TElement _first; }
[InlineArray(113)] struct ElementChunk113<TElement> { private TElement _first; }
[InlineArray(127)] struct ElementChunk127<TElement> { private TElement _first; }
[InlineArray(131)] struct ElementChunk131<TElement> { private TElement _first; }
[InlineArray(137)] struct ElementChunk137<TElement> { private TElement _first; }
[InlineArray(139)] struct ElementChunk139<TElement> { private TElement _first; }
[InlineArray(149)] struct ElementChunk149<TElement> { private TElement _first; }
[InlineArray(151)] struct ElementChunk151<TElement> { private TElement _first; }
[InlineArray(157)] struct ElementChunk157<TElement> { private TElement _first; }
[InlineArray(163)] struct ElementChunk163<TElement> { private TElement _first; }
[InlineArray(167)] struct ElementChunk167<TElement> { private TElement _first; }
[InlineArray(173)] struct ElementChunk173<TElement> { private TElement _first; }
[InlineArray(179)] struct ElementChunk179<TElement> { private TElement _first; }
[InlineArray(181)] struct ElementChunk181<TElement> { private TElement _first; }
[InlineArray(191)] struct ElementChunk191<TElement> { private TElement _first; }
[InlineArray(193)] struct ElementChunk193<TElement> { private TElement _first; }
[InlineArray(197)] struct ElementChunk197<TElement> { private TElement _first; }
[InlineArray(199)] struct ElementChunk199<TElement> { private TElement _first; }
[InlineArray(211)] struct ElementChunk211<TElement> { private TElement _first; }
[InlineArray(223)] struct ElementChunk223<TElement> { private TElement _first; }
[InlineArray(227)] struct ElementChunk227<TElement> { private TElement _first; }
[InlineArray(229)] struct ElementChunk229<TElement> { private TElement _first; }
[InlineArray(233)] struct ElementChunk233<TElement> { private TElement _first; }
[InlineArray(239)] struct ElementChunk239<TElement> { private TElement _first; }
[InlineArray(241)] struct ElementChunk241<TElement> { private TElement _first; }
[InlineArray(251)] struct ElementChunk251<TElement> { private TElement _first; }
[InlineArray(257)] struct ElementChunk257<TElement> { private TElement _first; }
[InlineArray(263)] struct ElementChunk263<TElement> { private TElement _first; }
[InlineArray(269)] struct ElementChunk269<TElement> { private TElement _first; }
[InlineArray(271)] struct ElementChunk271<TElement> { private TElement _first; }
[InlineArray(277)] struct ElementChunk277<TElement> { private TElement _first; }
[InlineArray(281)] struct ElementChunk281<TElement> { private TElement _first; }
[InlineArray(283)] struct ElementChunk283<TElement> { private TElement _first; }
[InlineArray(293)] struct ElementChunk293<TElement> { private TElement _first; }
[InlineArray(307)] struct ElementChunk307<TElement> { private TElement _first; }
[InlineArray(313)] struct ElementChunk313<TElement> { private TElement _first; }
[InlineArray(337)] struct ElementChunk337<TElement> { private TElement _first; }
[InlineArray(383)] struct ElementChunk383<TElement> { private TElement _first; }
[InlineArray(397)] struct ElementChunk397<TElement> { private TElement _first; }
[InlineArray(409)] struct ElementChunk409<TElement> { private TElement _first; }
[InlineArray(431)] struct ElementChunk431<TElement> { private TElement _first; }
[InlineArray(439)] struct ElementChunk439<TElement> { private TElement _first; }
[InlineArray(461)] struct ElementChunk461<TElement> { private TElement _first; }
[InlineArray(541)] struct ElementChunk541<TElement> { private TElement _first; }
[InlineArray(569)] struct ElementChunk569<TElement> { private TElement _first; }
[InlineArray(601)] struct ElementChunk601<TElement> { private TElement _first; }
[InlineArray(661)] struct ElementChunk661<TElement> { private TElement _first; }
[InlineArray(809)] struct ElementChunk809<TElement> { private TElement _first; }
[InlineArray(829)] struct ElementChunk829<TElement> { private TElement _first; }
[InlineArray(1129)] struct ElementChunk1129<TElement> { private TElement _first; }
[InlineArray(1213)] struct ElementChunk1213<TElement> { private TElement _first; }
[InlineArray(1489)] struct ElementChunk1489<TElement> { private TElement _first; }
[InlineArray(2621)] struct ElementChunk2621<TElement> { private TElement _first; }
[InlineArray(3449)] struct ElementChunk3449<TElement> { private TElement _first; }
[InlineArray(6553)] struct ElementChunk6553<TElement> { private TElement _first; }
[InlineArray(8191)] struct ElementChunk8191<TElement> { private TElement _first; }
