name: Bench

on:
  workflow_dispatch:

jobs:

  bench:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false

    env:
      DOTNET_VERSION: 8.0.x
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_TieredPGO: 1
      DOTNET_ReadyToRun: 0
      DOTNET_TC_QuickJitForLoops: 1

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nuget cache
      uses: actions/cache@v3
      with:
        path:
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      run: dotnet build -c Release

    - name: Run perft ${{ github.event.inputs.depth }} on ${{ github.event.inputs.fen }}
      run: dotnet run -c Release --no-build "bench"
      working-directory: ./src/Lynx.Cli
